### PR TITLE
feat: expose dedicated configuration

### LINKED ISSUE #34: Move ICE server config outside of python code to a config file
Currently ICE server config resides in [util.py](https://github.com/ambianic/peerjs-python/blob/master/src/peerjs/util.py)

It would be more convenient for users to edit ICE settings if they are in a separate and documented config file, e.g. webrtc-config.yaml

[This](https://github.com/ambianic/peerjs-python/blob/master/src/peerjs/util.py#L16) is the section that can be moved:
```
RTCConfiguration(
    iceServers=[
        RTCIceServer(
            urls=[
                "stun:stun1.l.google.com:19302",
                "stun:stun2.l.google.com:19302",
                "stun:stun3.l.google.com:19302",
                "stun:stun4.l.google.com:19302",
                "stun:stun.l.google.com:19302",
                "stun:stun.services.mozilla.com:3478",
                "stun:stunserver.org:3478",
                ]
                ),
        RTCIceServer(
            urls=['turn:numb.viagenie.ca'],
            username='webrtc@live.com',
            credential='muazkh'
            ),
        RTCIceServer(
            urls=['turn:192.158.29.39:3478?transport=udp'],
            credential='JZEOEt2V3Qb0y27GRntt2u2PAYA=',
            username='28224511:1379330808'
            ),
        RTCIceServer(
            urls=['turn:192.158.29.39:3478?transport=tcp'],
            credential='JZEOEt2V3Qb0y27GRntt2u2PAYA=',
            username='28224511:1379330808'
            ),
        RTCIceServer(
            urls=['turn:turn.bistri.com:80'],
            credential='homeo',
            username='homeo'
            ),
        RTCIceServer(
            urls=['turn:turn.anyfirewall.com:443?transport=tcp'],
            credential='webrtc',
            username='webrtc'
            ),
        RTCIceServer(
            urls=["turn:0.peerjs.com:3478"],
            username="peerjs",
            credential="peerjsp"
            )
        ]
    )
```

### PR DESCRIPTION
**Pull request by muka**
- store config in yaml
- expose ice servers

This should be good to close #34

### CODE REVIEW

**Comment by ivelin** [comment]
Very cool, @muka !

Would you like to add a section to README with a reference example to peerjs-config.yaml ?

**Comment by muka** [comment]
You are right, will add the config sample in the docs

**Comment by ivelin** [comment]
Merging this one so its not dangling. Let's do the docs update as a separate PR.

**Pull request merged**
