### PR TITLE
Attempt to fix the GHA build on Python 3.9

### PR DESCRIPTION
**Pull request by amotl**
Hi Ivelin,

this is just a humble attempt to check whether it might be able to solve #46 already.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by amotl** [comment]
I don't know why commit-lint-pr fails on my commit. Maybe you can give me a clue?

**Comment by ivelin** [comment]
Very cool. Thank you @amotl !

**Comment by ivelin** [comment]
> I don't know why commit-lint-pr fails on my commit. Maybe you can give me a clue?

It requires semantic release convention for commit message subject: https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by amotl** [comment]
Hi Ivelin,

> Very cool. Thank you @amotl!

You are welcome, glad to help.

> Commits require semantic release convention for commit message subject.

I already had a look at this and tried my best to satisfy this linter. Can you tell me where exactly the commit message failed on that? (I also tried with lowercase "f" but it didn't make any difference)
```
Fix: Attempt to make the CI build work on Python 3.9
```

With kind regards,
Andreas.

**Pull request merged**
